name: Build project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Use Node.js from .nvmrc

      uses: actions/setup-node@v7
      with:
        node-version-file: .nvmrc
        cache: "npm"

    - run: npm ci
    - run: npm run lint
    - run: npm run build
      env:
        ENV_GITHUB_TOKEN: ${{ secrets.ENV_GITHUB_TOKEN }}
    - run: ls out/

    # the build is to check the integrity of the project
    # the deployment is done by netlify.com
