name: Build project

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - shell: bash
      env:
        ENV_GITHUB_TOKEN: ${{ secrets.ENV_GITHUB_TOKEN }}
      run: |
        example-command "$ENV_GITHUB_TOKEN"

    # - uses: actions/checkout@v4
    # - name: Use Node.js 18.x
    #   env:
    #     ENV_GITHUB_TOKEN: ${{ secrets.ENV_GITHUB_TOKEN }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    # - run: npm ci
    # - run: npm run build
    # - run: ls out/
